### ISSUE TITLE
control state "controlled" 

### ISSUE THREAD

**Issue by savage7** [uhppoted/node-red-contrib-uhppoted#1]
I successfully integrated this wonderful set of node red nodes :) and got it working with minimal effort. Thanks alot for the great work you have done!!

There is only one thing I didn't get working:
Setting the control state to "controlled"
{"deviceId":223195309,"door":1,"control":"controlled"}
gives me:
"uhppoted::Error: invalid door control undefined"

the states "normally open/closed" both work. 
I used the mqtt solution before and setting "controlled" there worked. Also in your documentation the setting is mentioned as "controlled".

Is this a bug or do have an error in the json message?

Thanks for your help!

**Comment by uhppoted** [comment]
Typo in https://github.com/uhppoted/node-red-contrib-uhppoted/blob/4b6e7dc911c8381a7c848a7653ad2b9161415dc5/nodes/set-door-control.js#L32

`opcodes.controlled` should be `opcodes.Controlled`

**Comment by twystd** [comment]
Hi,

It's my first ever NPM module so am very happy (and relieved :-)) to hear you managed to get it working .. thanks!

I've pushed a hotfix to the `master` branch that corrects the typo, which slipped through both _eslint_ and manual testing (apologies) but I'd prefer to hold off on publishing an updated module until a unit test is in place and a related (but non-critical) issue is fixed. 

It's in a place where unit testing is particularly tricky so it may take a day or three. If you can use the development version that's great - if not and it's inconveniencing you, please let me know and I'll publish the hotfix immediately and the other fixes as a later release.

**Comment by savage7** [comment]
Oh thanks 🙏 for fixing this so fast. When looking at the code I didn't see the typo myself 🙈

Take your time with releasing the next version. I still have the mqtt version running, I just will disable the new flow in nodered and wait for your release.

**Comment by uhppoted** [comment]
v0.6.6 published to [NPM](https://www.npmjs.com/package/node-red-contrib-uhppoted) and [node-red](https://flows.nodered.org/node/node-red-contrib-uhppoted) and verified it is installable to the palette.

Thanks for your patience and feel free to let me know if you find anything else :-).
